spring:
  application:
    name: maria-lazaro
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER:maria2025}:${MONGO_PASSWORD:maria2025}@${MONGO_HOST:cluster0.heths.mongodb.net}/${MONGO_DB:sunat}retryWrites=true&w=majority&appName=Cluster0
      database: sunat
      auto-index-creation: true

# Configuración del servidor
server:
  port: 8080

# Configuración de la API externa
api:
  ruc:
    base-url: https://dniruc.apisperu.com/api/v1
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcmlhLmxhemFyb0B2YWxsZWdyYW5kZS5lZHUucGUifQ.pwDYAIkONqeiktGsiTSl_FTMsUMOjdroEdlOX8Gy3nQ

# Configuración de logging
logging:
  level:
    pe.edu.vallegrande.marialazaro: DEBUG
    org.springframework.data.mongodb: DEBUG
